# Generated by Django 3.2.7 on 2021-11-16 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0002_student_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='comments',
        ),
    ]
